// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace SecondOpinion.iOS.Views
{
    public partial class LauchScreenViewController : BaseViewController<AppInitializerViewModel>
	{
		public LauchScreenViewController (IntPtr handle) : base (handle) {
		}

		public override async void ViewDidLoad () {
            base.ViewDidLoad();

            var task = await ViewModel.ShouldGoToLogin();
            if (task) {
                var storyboard = UIStoryboard.FromName("Login", null);
                var initialVC = storyboard.InstantiateInitialViewController();
                SetAsMainScreen(initialVC);
            } else {
                var storyboard = UIStoryboard.FromName("Main", null);
                var initialVC = storyboard.InstantiateInitialViewController();
                SetAsMainScreen(initialVC);
            }
		}

        private void SetAsMainScreen(UIViewController viewController) {
            this.PresentViewController(viewController, true, null);
        }
	}
}
