// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using SecondOpinion.iOS.Views;
using SecondOpinion.ViewModels;
using System.Reactive.Disposables;

namespace SecondOpinion.iOS.UserList
{
    public partial class AddParticipantsViewController : BaseTableViewController<UserListViewModel>
	{
        public AddParticipantsViewController (IntPtr handle) {
            subscriptionDisposables = new CompositeDisposable();
        }

        public void SetViewModel(UserListViewModel viewModel) {
            this.ViewModel = viewModel;
        }

        public override void ViewDidLoad () {
            base.ViewDidLoad();
            if (ViewModel == null) {
                throw new ArgumentNullException("A ViewModel is required to be setted before it is shown");
            }
            TableView.RegisterClassForCellReuse(typeof(UserTableViewCell), "userListCell");
            TableView.DataSource = this;
            TableView.Delegate = this;
            TableView.AllowsMultipleSelection = true;
            this.Title = "Adicionar Participante";
        }

        public override void RowSelected (UITableView tableView , NSIndexPath indexPath) {

            //Update UI
            var cell = tableView.CellAt(indexPath);
            cell.Accessory = UITableViewCellAccessory.Checkmark;
            ViewModel.SelectItem.Execute(indexPath.Row);
        }

        public override void RowDeselected (UITableView tableView , NSIndexPath indexPath) {

            //Update UI
            var cell = tableView.CellAt(indexPath);
            cell.Accessory = UITableViewCellAccessory.None;
            ViewModel.DeselectItem.Execute(indexPath.Row);
        }

        public override nint NumberOfSections (UITableView tableView) {
            return 1;
        }

        public override nint RowsInSection (UITableView tableView , nint section) {
            return ViewModel.ContactList.Count;
        }

        public override UITableViewCell GetCell (UITableView tableView , NSIndexPath indexPath) {

            var cell = tableView.DequeueReusableCell("userListCell" , indexPath) as UserTableViewCell;
            var user = ViewModel.ContactList[indexPath.Row];

            cell.SetName(user.Item.Name);
            // Set photo

            if (user.Selected) {
                cell.Accessory = UITableViewCellAccessory.Checkmark;
            } else {
                cell.Accessory = UITableViewCellAccessory.None;
            }

            return cell;
        }

        /// <summary>
        /// Gos to group detail.
        /// </summary>
        /// <param name="sender">Sender.</param>
        partial void GoToGroupDetail (NSObject sender) {
            var storyBoard = UIStoryboard.FromName(StoryboardNames.ADD_PARTICIPANT , null);
            var viewController = storyBoard.InstantiateViewController("NewGroup") as GroupDetailViewController;

            viewController.SetSelectedUsers(ViewModel.GetSelectedUsers());
            this.NavigationController.PushViewController(viewController , true);
        }
	}
}
