// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using ReactiveUI;
using SecondOpinion.iOS.Views;
using SecondOpinion.Models;
using SecondOpinion.ViewModels;
using UIKit;

namespace SecondOpinion.iOS.UserList
{
	public partial class GroupDetailViewController : BaseViewController<CreateGroupViewModel>
	{
		public GroupDetailViewController (IntPtr handle) : base (handle) {
            SubscribeToViewModel();
            ViewModel.GoToDialogScreen += GoToDialogScreen;
        }

        /// <summary>
        /// Sets the selected users.
        /// </summary>
        /// <param name="selectedUsers">Selected users.</param>
        public void SetSelectedUsers(IList<UserContact> selectedUsers) {
            ViewModel.SelectedUsers = selectedUsers;
        }

        void SubscribeToViewModel() {
            this.Bind(ViewModel , vm => vm.GroupName , view => view.GroupSubject.Text);
            this.BindCommand(this.ViewModel , vm => vm.CreateGroup , view => view.CreateGroupButton);
        }

        void GoToDialogScreen(Dialog dialog) {
            //
        }
	}
}
